### ISSUE TITLE
Is this service suitable for webbrowser address resolution?

### ISSUE THREAD

**Issue by tobiascapin** [jmdns/jmdns#102]
I cannot understand if the mDns service registration can be used with a web browser address resolution in a local network without a DNS server.
For example, this registration:
`ServiceInfo.create("_http._tcp.local.", "myapp", 80, "path=/");`
Can be used for a web brower name resolution by this url: **http://myapp** or  **http://myapp.local** ?

**Comment by maggu2810** [comment]
You can use the A record for multicast DNS hostname resolution (so e.g. myapp.local to its IPv4 address). Same for AAAA.
This has nothing to do with a SRV record.

**Comment by maggu2810** [comment]
Have e.g. a look at:
* https://en.wikipedia.org/wiki/List_of_DNS_record_types
* https://tools.ietf.org/html/rfc6762
* https://tools.ietf.org/html/rfc6763

Normally you can configure your operating system if it should also consider to use mDNS for hostname resolution.
On linux machines you can e.g. use [nss-mdns](http://0pointer.de/lennart/projects/nss-mdns/)

**Comment by tobiascapin** [comment]
Ok, but can I server "A" record with jmDns?

**Comment by tobiascapin** [comment]
I looked for an example to use jmDns to reply "A" records but I did not find a solution, is it possibile? I found only how to provide or search for bonjour services.

**Comment by maggu2810** [comment]
I had have only a short look at the "public" (in an OSGi env - so only classes in the javax.jmdns package and not the impl ones) methods.
It seems that there is no such function.

**Comment by Stasik0** [comment]
Any solition?

**Comment by ViToni** [comment]
> Ok, but can I serve "A" record with jmDns?

No, you can't (as in: JmDNS is no replacemnet for a "conventional" DNS server)!

Reason is that the queries / responses are "usually" served via multicast and (again "usually") your hosts uses "normal" DNS for lookup (vie regular IPs not multicast groups).

**Comment by melloware** [comment]
@kaikreuzer this ticket can be closed it was a question that was answered.
