### ISSUE TITLE
binds wildcard interface

### ISSUE THREAD

**Issue by andyli** [jmdns/jmdns#119]
Similar to #69, when binding to a wildcard interface, e.g. 
```java
JmDNS jmdns = JmDNS.create(new InetSocketAddress(0).getAddress());
// ...
jmdns.registerService(serviceInfo);
```
clients will receive the `0.0.0.0` ip address but not the actual ip address.

Tested with JmDNS 3.5.1.

**Comment by ViToni** [comment]
@andyli Could you please check with 3.5.3?

**Comment by andyli** [comment]
I discontinued the project that used jmdns, and I don't think I can dig out the source code.
Feel free to close this if you think it has been fixed.

**Comment by kaikreuzer** [comment]
Let's close it then.
