### ISSUE TITLE
Publishing and Discovering services in Wide Area Networks

### ISSUE THREAD

**Issue by Manthan787** [jmdns/jmdns#131]
I'm using JmDNS in an android app and the server is supposed to be a laptop or PC. It works great in the home network when devices are connected to WiFi. 

However, when I run the same code on University network, it doesn't work. Is there a way to get it working on such networks?

**Comment by DanielMack** [comment]
most likely not - getting your multicast packets to leave your subnet requires administrative support, these packets need to be routed / forwarded ... which they are not by default.
