### ISSUE TITLE
org.slf4j.LoggerFactory not included?

### ISSUE THREAD

**Issue by chjan** [jmdns/jmdns#136]
Should this slf4j be integrated with this library, or should slf4j be added as a library to our project or else added to classpath? Which version of slf4j is needed?

MORE:  seems like some "binder" is missing fro sl4j?

**Comment by kaikreuzer** [comment]
Yes, for logging slf4j is required to be present at runtime, see https://github.com/jmdns/jmdns/blob/00e634dd7f555577c4c0bc58d37a2546cc85fb7e/pom.xml#L52-L56

The "binder", i.e. the used logging framework (logback, log4j, etc.) is up to you, check the slf4j docs.

**Comment by chjan** [comment]
This has been a timethief for me because slf4j reverts to NOP, but I would like the log active. I have tried with log4j (that I use), but no results. Could you be so kind to inform me what versions of binder I should be using? Thanks!  

Beyond that, the library is working fine, except I have not figured out yet how to successfully discover non-http services. Is there a quick win here too?

**Comment by angsuman** [comment]
I tried simple & jdk14 adapter but could not get any logging. 
BTW: I am trying to debug a DHCP related problem with chromecast-v2 library that I am using which uses jmDNS. Is there a simple way to turn on logging for jmDNS?

**Comment by dimgit** [comment]
Sometime ago, I used this - [https://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html](url)

**Comment by splatch** [comment]
Most of logging backends which you plug via `slf4j-xyz` dependencies requires some kind of configuration in order to set outputs.

This applies both log4j and jdk14 loggers. The `slf4j-simple` linked above rely on system properties so it can be easily tested. Without configuration it will just flush to stderr.
