### ISSUE TITLE
Discovery and Registration on macOS only works in special circumstances

### ISSUE THREAD

**Issue by schulz-m** [jmdns/jmdns#138]
I am using the jmDNS library with the device/client running on macOS or Raspbian and discover each other. Everything seems to work fine if the localhost on macOS redirects to the same local network as the Raspberry Pi is connected to.

Otherwise the behaviour is rather funny, for example with a server registering his service on Raspbian and a client trying to discover it on macOS:
* The client discovers the server only if the client is run afterwards.
* The client discovers the server also if another client is suddenly run on the RPi and seems to somehow communicate the mDNS info to the client on macOS
* If the server runs on macOS and the client on Raspbian, the client never finds the server.

I have seen the question on [stackoverflow](https://stackoverflow.com/questions/19533979/jmdns-doesnt-seem-to-work-at-all-on-mac-os-x) and also the pull request about [Apple Home sharing](https://github.com/jmdns/jmdns/pull/30) which I am not sure if it is related. The question on SO led me to believe that maybe the "standard mDNS deamons" on macOS interfere with the jmDNS functionality, so I tried to disable the processes according to [this blogpost](http://www.dgkapps.com/blog/osx-tips/osx-tips-turn-off-disable-bonjour-from-the-command-line/), which also seemed to work, as there were no mdns related processes running anymore - however it didn't solve the mentioned problems.

I hope I could make the issue somehow clear, it is rather confusing and might stem from my limited understanding about networking matters.

Any thoughts and inputs would be highly appreciated!

**Comment by klassm** [comment]
Hey @schulz-m - did you find a solution for your issues? 
I am currently encountering some issues that look like the ones you had on MacOS. I am registering a service, but #serviceAdded never gets called. Now I am wondering what to do  - I am not a fan of doing a separate implementation for MacOS :D

**Comment by ViToni** [comment]
@schulz-m Best approach is to define the network interface JmDNS should be listening to. The localhost might resolve to a different IP than you would expect.

**Comment by ViToni** [comment]
@klassm If you want to listen to your own announcement (serviceAdded) you need loopback enabled which might depend on OS/interface defaults. Otherwise only "the others" might get the announcement (which you could verify by having another JmDNS instance on another computer) .

**Comment by melloware** [comment]
@kaikreuzer according to @schulz-m this issue can be closed.
