### ISSUE TITLE
JmDNS does not discover services in Android AP mode

### ISSUE THREAD

**Issue by tobiasbianchi** [jmdns/jmdns#143]
I used JmDNS to successfully discover services while in a wireless network but when trying to discover services in AP mode no devices where ever found. Tried to make it work obtaining the multicast lock but nothing changed. I already searched but did not find any answer to this.

**Comment by ViToni** [comment]
@tobiasbianchi I wonder if you lokked at this issue and it's solution?

**Comment by tobiasbianchi** [comment]
@ViToni I don't think I had seen that issue, but tried it today without success.  I was already getting the address as in there, I created the multilock and also tried the recommendation of using only the address without hostname but it didn't work.

**Comment by Abu-Abdullah** [comment]
the same for me. it didn't work in AP mode. i follow the same code in:
https://github.com/becvert/cordova-plugin-zeroconf/blob/master/src/android/net/becvert/cordova/ZeroConf.java

this will listen to all interfaces and it can get the correct AP IP (192.168.43.1) which is standard for all android devices.

**Comment by Abu-Abdullah** [comment]
i can confirm this is working now with 3.5.4
