### ISSUE TITLE
ServiceInfoImpl.getPropertyString() does not seem to handle UTF-8 strings with Emoji

### ISSUE THREAD

**Issue by bubbleguuum** [jmdns/jmdns#151]
Easy to test with a Chromecast device:

- in the Google Home app, assign it a name with some Emoji
- discover these devices via jMDNS
- get the "fn" property:  

String fn = serviceInfo.getStringProperty(fn);

With v3.5.1, null was returned.
With v3.5.3 a value is returned but with Emoji characters as garbage:

For &#128514;test, the fn string value has garbled characters preceding test.

The issue is definitely in ByteWranger.readUTF(), because replacing it with the String constructor works:

```
String getPropertyString(ServiceInfo info, String name) {
	byte data[]  = info.getPropertyBytes(name);
	if (data == null) {
	      return null;
	 }
	 if (data == ByteWrangler.NO_VALUE) {
	        return "true";
	  }
	
         // return ByteWrangler.readUTF(data, 0, data.length);
	 try {
	     return new String(data, "UTF-8");
	} catch (UnsupportedEncodingException e) {
	   return null;
	}
}
```

**Comment by ViToni** [comment]
@bubbleguuum Could you try to reproduce the issue with jmdns-3.5.2?

**Comment by bubbleguuum** [comment]
3.5.2 has the same issue and even return a null "fn"property when fn in my test case has 3 prepended and 3 appended Emoji symbols surrounding regular text. Any reason why the String constructor is not simply used in place of custom code (ByteWrangler) ?

**Comment by bubbleguuum** [comment]
I tested you branch (disabling my workaround) and I confirm it works fine and fixes the problem (as expected).
