### ISSUE TITLE
Compatible wth Java 9 module system

### ISSUE THREAD

**Issue by longkerdandy** [jmdns/jmdns#155]
Java 9 now officially released, and includs the java module platform system (jigsaw project).
There are two ways to make jmdns compatible with a new java module project:
1. Add "Automatic-Module-Name" MANIFEST.MF entry.  (the easy way)
2. Package and publish jmdns as java 9 module by adding module-info.java etc.

By default, the java 9 system will give jmdns a autiomatic module name "jmdns" which comes from its file name. This may result future update issue because the prefered module name id likely to be "org.jmdns".
Please refer to this article to detail information: http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

**Comment by kaikreuzer** [comment]
Option 2 hopefully should not be hard. Would you like to come up with a PR that adds such module information?

**Comment by rfcom** [comment]
Just add the `Automatic-Module-Name` entry to the `maven-jar-plugin` configuration in the `pom.xml` like this:
```
    <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        ...
        <configuration>
            <archive>
                ...
                <manifestEntries>
                    ...
                    <Automatic-Module-Name>javax.jmdns</Automatic-Module-Name>
                </manifestEntries>
            </archive>
        </configuration>
    </plugin>
```
this will make the JAR file ready for the java module system.

**Comment by melloware** [comment]
This is now done should this ticket be closed?
