### ISSUE TITLE
Request for 3.5.4 release to deploy #150

### ISSUE THREAD

**Issue by emcniece** [jmdns/jmdns#156]
Hello! Would it be possible to publish a new release so that we can use #150 from the Maven repo at a pinned version? This recent PR solves a handful of issues across a few projects - this is summarized at https://github.com/becvert/cordova-plugin-zeroconf/issues/63#issuecomment-378483860

#150 Locally potentially related issues:

- #143 
- #116 
- #107 

We look forward to helping a bunch of `cordova-plugin-zeroconf` users with this update. Thanks for your help!

**Comment by kaikreuzer** [comment]
Hi Eric! Yes, you're right, it is time for a new release. I'll try to do that within the next 2 weeks.

**Comment by Abu-Abdullah** [comment]
please update the dependency from slf4j-api-1.7.16.jar to slf4j-api-1.7.25.jar

**Comment by emcniece** [comment]
@Abu-Abdullah please [open a new issue](https://github.com/jmdns/jmdns/issues/new) with your request and an explanation for doing so.

**Comment by kaikreuzer** [comment]
> please update the dependency from slf4j-api-1.7.16.jar to slf4j-api-1.7.25.jar

@Abu-Abdullah Done with https://github.com/jmdns/jmdns/pull/158

**Comment by kaikreuzer** [comment]
Done! https://github.com/jmdns/jmdns/releases/tag/jmdns-3.5.4
