### ISSUE TITLE
Services that were removed are reported as resolved.

### ISSUE THREAD

**Issue by IvanBoychevMarinov** [jmdns/jmdns#170]
Sometimes a service that was removed gets reported as resolved at some later point. I think I have a fix for this, but I need you guys to take a look. Basically in the method "updateRecord" in the JmDNSImpl when a serviceInfo is about to be removed it is not removed from the listeners list which is basically a list of ServiceInfo instances. I believe that afterwards this ServiceInfo object is not removed at all and somtimes this results in sending Resolved events for this service info.

**Comment by bk138** [comment]
Same here. @IvanBoychevMarinov care to post a patch?

**Comment by IvanBoychevMarinov** [comment]
Hi, sorry about responding this late. I actually have a pull request for this.
https://github.com/jmdns/jmdns/pull/172

I'm witnessing the same behavior here. serviceResolved is fired I would say randomly. With the changes above this never happens.
I just wanted to see it verified because it works for me in isolation, but I'm not sure I can think of all of the use-cases. 
Take a look and feel free to use it.

**Comment by IvanBoychevMarinov** [comment]
Hi, @bk138. I was wondering if you managed to get my changes and if the y are working for you. As you know I'm not completely sure if this is not breaking some other functionality so any input would be helpful.

**Comment by bk138** [comment]
Hi @IvanBoychevMarinov I'll give them a try ASAP, hopefully this week.

**Comment by bk138** [comment]
@IvanBoychevMarinov I could try out your patch. What's changed with respect to https://github.com/jmdns/jmdns/issues/170#issuecomment-453755078 is that `serviceResolved` is not firing anymore for a seen-then-gone service, _but_ I still see `serviceResolved` firing a lot for up-and-advertising services. So it's definitely an improvement, though jmdns-3.4.1 still behaves differently with only one  `serviceResolved`  per service.

**Comment by IvanBoychevMarinov** [comment]
@bk138 Unfortunatelly I don't have deep knowledge of the development of the project and the various versions. I think the reason must be the same "listener". I'm not sure why are these in there and what should be the expected behaviour. As far as I understand whenever a record is received, all of the "listeners" for a given type are notified as resolved. Even if the record comes from another service of the same type. These are just suggestions and I think you can try  to determine the exact *listener* for the service and notify only this one.
