### ISSUE TITLE
Allow escape of dot in instance name

### ISSUE THREAD

**Issue by mattiasbe** [jmdns/jmdns#180]
Allow dots in instance names as per rfc 6763. According to rfc6763 instance names are allowed to contain any characters, including dots. They recommend escaping them if concatenating all the parts internally.

See section 4.3:
”4.3. Internal Handling of Names”
https://github.com/jmdns/jmdns/blob/master/devdocs/txt/rfc6763.txt

Also see this from avahi:
“Notes on DNS Name Escaping”
https://code.woboq.org/qt5/include/avahi-compat-libdns_sd/dns_sd.h.html

The reason for this requested support is that the European ITxPT public transport standard is using an additional extra field in the instance containing the separator dot.

Please see pull request #179 for a suggested minimum impact (?) version

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/jmdns/jmdns/pull/179.

**Comment by axlsml** [comment]
I also created an issue according to contribution guidelines: https://github.com/jmdns/jmdns/issues/191
