### ISSUE TITLE
How to use it in Android?

### ISSUE THREAD

**Issue by dtboy1995** [jmdns/jmdns#181]
How to use it in Android? thanks a lot

**Comment by bk138** [comment]
You basically have to run jmds in a separate thread, like https://github.com/bk138/multivnc/blob/master/android/app/src/main/java/com/coboltforge/dontmind/multivnc/MDNSService.java. The Service encapsulation is optional.

**Comment by dtboy1995** [comment]
@bk138 thanks a lot.
