### ISSUE TITLE
OOM and high CPU caused by door camera

### ISSUE THREAD

**Issue by ivenhov** [jmdns/jmdns#186]
Hi all

I have a strange problem caused by our door bell camera discovered through mDNS
Problem eventually leads to 100% CPU and OutOfMemory errors on my JVM.

Camera sends packet which looks like this

`
000084000000000e00000000184772616e6473747265616d2d303030423832423834364434056c6f63616c00000180010000007800040b0100320235300130013102313107696e2d6164647204617261700000018001000000780002c00c224772616e6473747265616d2047445333373130202d20303030423832423834364434055f68747470045f746370056c6f63616c00002180010000007800080000000001bbc00cc05e0010800100001194000100095f7365727669636573075f646e732d7364045f756470056c6f63616c00000c0001000011940002c081c081000c0001000011940002c05e224772616e6473747265616d2047445333373130202d20303030423832423834364434055f72747370045f746370056c6f63616c000021800100000078000800000000022ac00cc0ea0010800100001194000100c0b2000c0001000011940002c0eac0ea000c0001000011940002c0ea224772616e6473747265616d2047445333373130202d20303030423832423834364434125f4772616e6473747265616d2d766964656f045f746370056c6f63616c00002180010000007800080000000001bbc00cc15a0010800100001194000100c0b2000c0001000011940002c0eac0ea000c0001000011940002c15a
`

This can be broken down as follows (bulk at the end omitted)

```
Some header
000084000000000e00000000 

First Type A answer
18 4772616e6473747265616d2d303030423832423834364434056c6f63616c00000180010000007800040b010032

2nd Type A record
02 35300130013102313107696e2d61646472046172617000000180010000007800 02 c00c
```
I have no problem with first answer
`[IPv4Address@1341712829 type: TYPE_A index 1, class: CLASS_IN index 1-unique, name: Grandstream-000B82B846D4.local. ttl: '0/120' address: '11.1.0.50']`

But the 2nd one is funny. Last part 02 c00c indicates there are 2 bytes for records data, and that really should be 4 bytes as far as I can tell as this is Inet4Address

This looks like a bug in the camera. We've upgraded to the latest firmware but the problem stays. We will be in touch with manufacturer as well.

The thing is JmDNS still creates record but with IP which is null.
```
java.net.UnknownHostException: addr is of illegal length
	at java.net.InetAddress.getByAddress(InetAddress.java:1042)
	at java.net.InetAddress.getByAddress(InetAddress.java:1439)
	at javax.jmdns.impl.DNSRecord$Address.<init>(DNSRecord.java:307)
	at javax.jmdns.impl.DNSRecord$IPv4Address.<init>(DNSRecord.java:211)
	at javax.jmdns.impl.DNSIncoming.readAnswer(DNSIncoming.java:326)
	at javax.jmdns.impl.DNSIncoming.<init>(DNSIncoming.java:234)
	at javax.jmdns.impl.SocketListener.run(SocketListener.java:50)
```

Later on more records are added they expire because they never match through equality check

```
INFO  2019-04-03 15:18:53.796  SocketListener(DESKTOP-D5IPNMD.local.)   Inv   sameValue()                    Failed to compare addresses of DNSRecords      (DNSRecord.java:336)
java.lang.NullPointerException: null
	at javax.jmdns.impl.DNSRecord$Address.sameValue(DNSRecord.java:334)
	at javax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1384)
	at javax.jmdns.impl.JmDNSImpl.handleResponse(JmDNSImpl.java:1462)
	at javax.jmdns.impl.SocketListener.run(SocketListener.java:61)
```

Also eviction does not happen 
```
INFO  2019-04-03 15:20:00.626  JmDNS(DESKTOP-D5IPNMD.local.).Timer      Inv   sameValue()                    Failed to compare addresses of DNSRecords      (DNSRecord.java:336)
java.lang.NullPointerException: null
	at javax.jmdns.impl.DNSRecord$Address.sameValue(DNSRecord.java:334)
	at javax.jmdns.impl.DNSRecord.equals(DNSRecord.java:66)
	at java.util.ArrayList.remove(ArrayList.java:510)
	at javax.jmdns.impl.DNSCache.removeDNSEntry(DNSCache.java:237)
	at javax.jmdns.impl.JmDNSImpl.cleanCache(JmDNSImpl.java:1888)
	at javax.jmdns.impl.tasks.RecordReaper.run(RecordReaper.java:56)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

This causes pile up of entries and soon very high CPU due to entry comparison, exceptions thrown and logged. In my case SLF4J was configured to NOPLogger for some reason, which may contributed to 100% CPU due to no-ops.

My understanding of DNS is quite vague, but it does look like a firmware bug.
- is it possible that there is a flavour of Type A answer which can use 2 bytes only?
- is there anything we could do to fix this and avoid ripple effect in JmDNS library?

My thought would be to do something like that in DNSIncoming line 326:

```
                if (len == 4) 
                    rec = new DNSRecord.IPv4Address(domain, recordClass, unique, ttl, _messageInputStream.readBytes(len));
                else 
                    _messageInputStream.skip(len);
```

I appreciate this is solving problem created by something else (if it is in fact firmware problem), but I would like to avoid mentioned problems.

Regards
Daniel

**Comment by joerg1985** [comment]
@ivenhov I have two questions about the merged PR:

1. The 'Copyright Object Matrix 2017' header of the `SimpleLockManager` looks like this has been taken from somewhere. Is this okay from a licencing point of view to use it here?

2. The locking machanism inside the `SimpleLockManager` does not fullfill the requiremets of a Lock in Java in my mind. More concrete, this is only blocking without ensuring memory synchronization is done.
   (see topic 'Memory Synchronization' in the javadoc of `java.util.concurrent.locks.Lock`).
   Therefore i think this change does break the thread safty of the cache, or did i miss something?

**Comment by kaikreuzer** [comment]
> The 'Copyright Object Matrix 2017' header

Good catch, I missed that when merging the PR - this definitely needs to be clarified!

**Comment by ivenhov** [comment]
1. Header has been auto-generated by my Eclipse. Apologies I missed that. 
This should be removed to avoid any future questions regarding licensing etc.
Let me know if you wan't me to create PR for that

2. Correct, returned object `Locked` it's not a Java `Lock` but more like a representation of a locked resource.
The only operation for it is `close()` to use in try-with-resource.
Memory visibility should be provided by atomicity of `putIfAbsent` in `ConcurrentHashMap` and its internal synchronization.

**Comment by joerg1985** [comment]
@ivenhov yes memory visibility for the `Locked` is provided by the `ConcurrentHashMap`, but not for everything else a regular `Lock` / `synchonized` block would take care. [Not even the state of a mutable value inside a `ConcurrentHashMap` might be correct², only the correct² value will be ensured](https://stackoverflow.com/questions/18030570/are-mutable-fields-in-a-pojo-object-threadsafe-if-stored-in-a-concurrenthashmap). 
So i am talking about how the changes to the objects used inside this lock are made visible to other threads?
This was the use of the removed `synchonized` block and there is IMHO no replacement to it.

² in terms of happens before

**Comment by ivenhov** [comment]
Based on 
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/package-summary.html
and
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentMap.html

Specifically
"Actions in a thread prior to placing an object into any concurrent collection happen-before actions subsequent to the access or removal of that element from the collection in another thread."

and for ConcurrentMap
"Memory consistency effects: As with other concurrent collections, actions in a thread prior to placing an object into a ConcurrentMap as a key or value happen-before actions subsequent to the access or removal of that object from the ConcurrentMap in another thread."

The way I understand it put/get/remove creates a memory barrier and guarantees visibility, including state of the POJO objects
Looking at DNSCache.addDNSEntry()
```
    public boolean addDNSEntry(DNSEntry dnsEntry) {
        if (dnsEntry == null)
            return false;
        String key = dnsEntry.getKey();
        Locked lock = _lm.lock(key);
        try {
            List<DNSEntry> entryList = this.get(key);
            if (entryList == null) {
                entryList = new ArrayList<DNSEntry>();
                entryList.add(dnsEntry);
                this.put(key, entryList);
            } else {
                entryList.add(dnsEntry);                
            }
        } finally {
            lock.close();
        }
        return true;
    }
```

Thread A calls  _lm.lock() i.e put() operation on the map.
This means everything that happened in another thread B prior to thread B calling lock.close() and map.remove() is visible.

Thread-safety of the ArrayList and DNSEntry instances is guaranteed by acquiring a Locked object.

The same guarantees happens-before are provided by synchronized { }, except that it also provides exclusivity.
