### ISSUE TITLE
Allow Dots in Instance Names (Service Subscription)

### ISSUE THREAD

**Issue by axlsml** [jmdns/jmdns#191]
Same issue as https://github.com/jmdns/jmdns/issues/180 - just here it is considering the subscription part.

The current JmDNS implementation is not able to subscribe to the following service:
> instancename._apc._itxpt_http._tcp.local.

Please note the dot in the instance name. Instance name is **instancename._apc** including the dot. What JmDNS decodes instead for the above type string is:
* instance: instancename :x: (_expected_: instancename._apc)
* application: apc._itxpt_http :x: (_expected_: itxpt_http)
* domain: local :heavy_check_mark:
* protocol: tcp :heavy_check_mark:

**TL; DR:** The following unit test must pass:

```@Test
    public void testDecodeITxPTServiceType() {
        String type = "instancename._apc._itxpt_http._tcp.local.";

        Map<Fields, String> map = ServiceInfoImpl.decodeQualifiedNameMapForType(type);

        assertEquals("We did not get the right domain:", "local", map.get(Fields.Domain));
        assertEquals("We did not get the right protocol:", "tcp", map.get(Fields.Protocol));
        assertEquals("We did not get the right application:", "itxpt_http", map.get(Fields.Application));
        assertEquals("We did not get the right name:", "instancename._apc", map.get(Fields.Instance));
        assertEquals("We did not get the right subtype:", "", map.get(Fields.Subtype));
    }
```

**Comment by rolfchess** [comment]
We ran into this problem too.
The pull reqeuest with the fix for this issue is looking really nice: https://github.com/jmdns/jmdns/pull/190

Dear jmDNS team, please indicate when this pull request will be integrated and when this fix will be available in an official release.

**Comment by melloware** [comment]
@kaikreuzer this can be closed as the PR was merged long ago.
