### ISSUE TITLE
DNSRecord does not support IPv4-mapped IPv6 addresses

### ISSUE THREAD

**Issue by edgsousa** [jmdns/jmdns#202]
Using 3.5.5
A `toString()`of the record prints:
`[IPv6Address@633075331 type: TYPE_AAAA index 28, class: CLASS_IN index 1-unique, name: test ttl: '3599999/3600000' address: ['127.0.0.1']`]
```
java.lang.ClassCastException: class java.net.Inet4Address cannot be cast to class java.net.Inet6Address (java.net.Inet4Address and java.net.Inet6Address are in module java.base of loader 'bootstrap')

	at javax.jmdns.impl.DNSRecord$IPv6Address.getServiceInfo(DNSRecord.java:285)
```

[Test case demonstrating this](https://gist.github.com/edgsousa/02f37374f2f5df3975790faff0330391)

**Comment by kaikreuzer** [comment]
Fixed with https://github.com/jmdns/jmdns/pull/209.
