### ISSUE TITLE
Android R8 Desugaring removes putIfAbsent method on DNSCache

### ISSUE THREAD

**Issue by MWingbermuhle** [jmdns/jmdns#205]
We are using jmdns as a library within our own Android library.
Within our Android libraries, we would like to use Java 8 features, which in short means that we need to enable R8 desugaring (https://developer.android.com/studio/write/java8-support).

With desugaring enabled, we are facing a crash inside the jmdns library, specifically inside `DNSCache`, where the `putIfAbsent` method is being removed. Why R8 does this, we don't know. 

This results in runtime crashes with logging similar to this:
```
java.lang.NoSuchMethodError: No static method $default$putIfAbsent(Ljava/util/concurrent/ConcurrentMap;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lj$/util/concurrent/ConcurrentMap$-CC; or its super classes (declaration of 'j$.util.concurrent.ConcurrentMap$-CC' appears in base.apk!classes2.dex)
        at javax.jmdns.impl.DNSCache.putIfAbsent(Unknown Source:0)
        at javax.jmdns.impl.DNSCache.addDNSEntry(SourceFile:2)
        at javax.jmdns.impl.JmDNSImpl.handleRecord(SourceFile:34)
        at javax.jmdns.impl.JmDNSImpl.handleResponse(SourceFile:5)
        at javax.jmdns.impl.SocketListener.run(SourceFile:15)
```

After some additional research (including checking out the jmdns code and modifying it) we found a possible fix, where instead of letting `DNSCache` inherit from a `ConcurrentHashMap`, we are giving it a private instance of it.
I also improved the synchronization around that code, since we can now synchronize on the map instead of the local entryList.

**Comment by HPSudip** [comment]
Hi @MWingbermuhle , we also use Jmdns and started facing this crash recently in our project after enabling desugaring support. Thanks for the issue and the fix.

**Comment by kaikreuzer** [comment]
Fixed with https://github.com/jmdns/jmdns/pull/208.
