### ISSUE TITLE
Sample Browser is not user friendly

### ISSUE THREAD

**Issue by amartinwest** [jmdns/jmdns#212]
Here is more user friendly version.

[Browser.zip](https://github.com/jmdns/jmdns/files/5519071/Browser.zip)

**Comment by melloware** [comment]
Modified and improved yours even futher.  Centers on Screen for exactly 1/2 the screen size. Details uses Fixed Font.

[MdnsBrowser.zip](https://github.com/user-attachments/files/17167864/MdnsBrowser.zip)

**Comment by melloware** [comment]
@kaikreuzer this can very closed now.
