### ISSUE TITLE
Instanciating JmmDns is slow

### ISSUE THREAD

**Issue by NewLunarFire** [jmdns/jmdns#215]
I have had issues with the multihomed JmDns class where getting the instance of JmmDns took up to 30 seconds.

I have narrowed down the issue to the `JmDNS.create` calls to create new JmDns instance when the Network Topology changes, which is done multiple times when creating the JmmDns instance because it calls this function for every network interface.

In turn, creating those JmDns instances because they are created without specifing a name parameter to the `JmDns.create` function. When a name is not provided, the JmDns constructor will call `InetAddress.getHostName()` to find a suitable name for the instance.

It is known that calling `InetAddress.getHostName()` can take several seconds because it does a reverse hostname lookup. Doing so multiple times adds up to a significant amount of time.

I have done a small test program to test the calls to `JmDNS.create` with and without the name parameter. Here is the code and results for this:

```java
public class JmDNSSample
{
    public static void main(String[] args) throws IOException
    {
        long startTime, endTime;
        startTime = System.nanoTime();
        NetworkInterface.networkInterfaces()
            .flatMap(NetworkInterface::inetAddresses)
            .map(JmDNSSample::createInstanceWithHostNameLookup)
            .collect(Collectors.toList());

        endTime = System.nanoTime();

        System.out.println("Creating instances with hostname lookup took " + (endTime - startTime) / 1000000000.0 + "s");

        startTime = System.nanoTime();
        NetworkInterface.networkInterfaces()
            .flatMap(NetworkInterface::inetAddresses)
            .map(JmDNSSample::createInstanceWithoutHostNameLookup)
            .collect(Collectors.toList());

        endTime = System.nanoTime();

        System.out.println("Creating instances without hostname lookup took " + (endTime - startTime) / 1000000000.0 + "ns");
    }

    private static JmDNS createInstanceWithHostNameLookup(InetAddress addr)
    {
        try
        {
            return JmDNS.create(addr);
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }

        return null;
    }

    private static JmDNS createInstanceWithoutHostNameLookup(InetAddress addr)
    {
        try
        {
            return JmDNS.create(addr, "HostName");
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }

        return null;
    }
```

```
Creating instances with hostname lookup took 36.2592562s
Creating instances without hostname lookup took 0.5910996ns
```

We can see a significant improvement with a "hard-coded" name for `JmDNS.create` invocations. So, I suggest we had a way to specify a name that will be used in all calls to `JmDNS.create`. It can either be a `setName` function in JmmDNS, or we could add a function to ClassDelegate like `JmDNS createInstance(final InetAddress addr)` to let the user have more control over the creation of the JmDNS instances by the JmmDNS class, or any other solution that will allow me to skip the reverse hostname lookup when creating the JmmDNS instance.

For now as a workaround I can copy the implementation of JmmDNS and just change the offending line, but I would prefer we give more control to the user to create JmDNS instances used by JmmDNS.

**Comment by kaikreuzer** [comment]
Sounds like a worthwhile enhancement. Feel free to come up with a PR for it!
