### ISSUE TITLE
jmDNS Issue?

### ISSUE THREAD

**Issue by alundqvi** [jmdns/jmdns#217]
I am using the HAP-Java as a simple Bridge. HAP Java is built upon jmDNS 3.5.6 so the latest as I believe. I can register in my Home app on iPhone as soon as the mDNS is visible.

First start often fails but after restart of the Bridge I can see the announcement on my Mac using sd-dns command. I register the Bridge and one switch I have registered. All fine and the Home App shows the Bridge and the Switch.

Now very soon after the registration the Phone/iPad indicates a failure, Can't connect to the Accessory. Then again connection is available. This is ongoing.

If I look at the sd-dns -B output (See below) I can see Add of the announcement. Then 1-3 minutes later Rmv so it is removed. Then again 1-3 minutes later it is Added again. And it is clear that during the period when it is Removed the service is not working but it starts again as soon as the next Add appears.

Is this seen by others? I am running the Bridge on a raspberry pi 4 Buster. I have tried to both stop and as well have Avahi running, as I believe it can interfere. 

Output from sd-dns -B:

19:30:44.950 Add 2 17 local. _hap._tcp. MyNewestTestBridge
19:33:54.092 Rmv 0 17 local. _hap._tcp. MyNewestTestBridge
19:36:51.017 Add 2 17 local. _hap._tcp. MyNewestTestBridge
19:39:55.727 Rmv 0 17 local. _hap._tcp. MyNewestTestBridge
19:41:47.931 Add 2 17 local. _hap._tcp. MyNewestTestBridge
19:42:57.181 Rmv 0 17 local. _hap._tcp. MyNewestTestBridge
19:47:35.785 Add 2 17 local. _hap._tcp. MyNewestTestBridge

Output from sd-dns -Z

_hap._tcp PTR MyNewestTestBridge._hap._tcp
MyNewestTestBridge._hap._tcp SRV 0 0 9123 lundqvistpi.local. ; Replace with unicast FQDN of target host
MyNewestTestBridge._hap._tcp TXT "c#=1" "s#=1" "ff=0" "sf=0" "sh=lhjaKg==" "ci=1" "md=MyNewestTestBridge" "id=9a:9b:44:29:77:ee"

/Anders

**Comment by melloware** [comment]
@alundqvi is this still an issue or can it be closed?

**Comment by alundqvi** [comment]
My system works... Hence I have not done any more investigations... So please close it!

**Comment by alundqvi** [comment]
Closing

**Comment by melloware** [comment]
Thanks for closing!
