### ISSUE TITLE
Make mdns group address configurable

### ISSUE THREAD

**Issue by NewLunarFire** [jmdns/jmdns#222]
The MDNS_GROUP and MDNS_GROUP_IPV6 constants should be configurable, at least through a system property. The 224.0.0.0/24 subnet is link-only and would not be forwarded across subnets, same for the FF02 subnet in IPv6. Changing the address to be on the 239.0.0.0/24 (or FF04 in IPv6) would solve my issue and forward mdns packets across subnets.

So my suggestion is to make those addresses configurable with a system property and have the defaults be the addresses defined in the mdns spec. It can then be overriden using either `-Dnet.mdns.ipv4=239.0.0.251` as  a vm argument or `System.setProperty("net.mdns.ipv4", "239.0.0.251")` in Java code. The multicast port is already configurable this way.

```
public static final String MDNS_GROUP = System.getProperty("net.mdns.ipv4", "224.0.0.251");
public static final String MDNS_GROUP_IPV6 = System.getProperty("net.mdns.ipv6", "FF02::FB");
```

I will soon submit my patch as a PR.

**Comment by kaikreuzer** [comment]
@NewLunarFire I plan to do a new jmDNS release soon. I can try to include your PR if you manage to create it in the next days.

**Comment by NewLunarFire** [comment]
@kaikreuzer I have opened the PR yesterday.
