### ISSUE TITLE
Overly extensive and superfluous Logging in DNSIncoming.readAnswer

### ISSUE THREAD

**Issue by geroyche** [jmdns/jmdns#229]
I see my log being spammed.
There are sort of two issues here:

1. how can logging be held to an acceptable level
2. what triggers the error

Regarding 1.:
in my case, the following condition is true, and I get a substantial log entry, as I have 320 answers in that array:
https://github.com/jmdns/jmdns/blob/main/src/main/java/javax/jmdns/impl/DNSIncoming.java#L312

then, TYPE_UNKNOWN is not handled in the subsequent condition here:
https://github.com/jmdns/jmdns/blob/main/src/main/java/javax/jmdns/impl/DNSIncoming.java#L317
which leads to what's essentially a second full printout of 320 answers.

I would submit a pull request, but I am not deep enough into the code yet to understand what would be the best solution... early returns? a simple && (type != DNSRecordType.TYPE_UNKNOWN) ?

also: I question whether print() should actually do all that it does when the application is not deliberately set to debug mode?

Regarding 2:
The parser seems to take issues with this packet, and I am not sure why, but I am also not really firm in DNS payloads.
Here's the start of the packet dump:

` 0: 00008400000001a9 000000000f4c4150 544f502d49363238 35434d54056c6f63 `
aka
`........ .....LAP TOP-I628 5CMT.local......`

apparently the parser considers this a compressed name, but then fails to find the actual name

```
Jun 02, 2021 2:55:45 PM javax.jmdns.impl.DNSIncoming$MessageInputStream readName
WARNING: Bad domain name: possible circular name detected. Bad offset: 0x3fff at 0x230a
Jun 02, 2021 2:55:45 PM javax.jmdns.impl.constants.DNSRecordType typeForIndex
WARNING: Could not find record type for index: 65535
Jun 02, 2021 2:55:45 PM javax.jmdns.impl.DNSIncoming readAnswer
WARNING: Could not find record type. domain: 
```

then the first print, and then

```
un 02, 2021 2:55:45 PM javax.jmdns.impl.constants.DNSRecordClass classForIndex
WARNING: Could not find record class for index: 65535
Jun 02, 2021 2:55:45 PM javax.jmdns.impl.DNSIncoming readAnswer
WARNING: Could not find record class. domain:  type: TYPE_IGNORE index 0
```
and the second print...

note that this log references a machine I do not currently have access to. I cannot do much more debugging.

**Comment by melloware** [comment]
Can this be closed now that the PRs have been merged?
