### ISSUE TITLE
Fail to get correct Bonjour Name. 4byte character is not coverted correctly.

### ISSUE THREAD

**Issue by ishikmat** [jmdns/jmdns#232]
### I want to discuss about this code.  
jmDNS version: 3.5.7
`src\main\java\javax\jmdns\impl\DNSEntry.java(243):         dout.write(this.getName().getBytes("UTF8")); `

### Discuss about.  
I think `getBytes("UTF8")` is wrong, and `getBytes("UTF-8")` is correct, is it right?

I guess like below, so could you confirm.
- Does `getBytes("UTF8")` work similar to `getByte()` ? 
- and it is not correctly converted to **Byte of UTF-8** , and coverted **other encoding** ?
- and ***other encoding*** is not support 4byte character, and cause below problem?

If this is wrong, sorry.

### Problem I encounterd
1. We set the `αβ耳𡧃abc` as bonjour name.
        UTF-8 code α:0xceb1, β:0xceb2, 耳:0xe880b3, 𡧃:0xf0a1a783, a:0x61, b:0x62, c:0x63
2. we got bellow binary from jmdns as bonjour name,
        `1110110001 1110110010 1000000000110011 1100000001 1001110011 1100001 1100010 1100011`
3. and it could be converted as  `αβ耳́ɳabc` 
       Problem: UTF-8 4-byte characters (𡧃: 0xf0a1a783) are not displayed correctly.

**Comment by ishikmat** [comment]
@kaikreuzer 
thank you for response, and I understand you don't have specific plan yet.
I'm looking forward to the next release towards end of the year!

**Comment by YusukeShinosaki** [comment]
Hi @kaikreuzer 
I'm yusuke who is succeeser of @ishikmat, could you let me know the latest status of this issue?

**Comment by kaikreuzer** [comment]
Thank you for the ping, @YusukeShinosaki!
I indeed forgot about doing a new release end of last year.
I've just merged the last open PR and built a 3.5.8 - see https://github.com/jmdns/jmdns/releases/tag/3.5.8.

I hope this helps you!

**Comment by YusukeShinosaki** [comment]
@kaikreuzer 
Thank you for your support.
When I clicked [Maven Central](https://repo1.maven.org/maven2/org/jmdns/jmdns/3.5.8), it shows 404 Not Found.
Could you please confirm the link or do I need something to access this URL?

**Comment by kaikreuzer** [comment]
@YusukeShinosaki The link was missing a trailing slash, I have corrected it on the release notes. Try this: https://repo1.maven.org/maven2/org/jmdns/jmdns/3.5.8/

**Comment by YusukeShinosaki** [comment]
@kaikreuzer 
Thank you! I confirmed access.
