### ISSUE TITLE
Call getServiceInfo periodially, it returns null sometimes

### ISSUE THREAD

**Issue by zhangl22000** [jmdns/jmdns#234]
Environment: 
1. There are 120 systems which registers a serivce seperately. 
2. Each system calls getServiceInfo every 100 seconds.

getServiceInfo get null value sometimes.

Root cause:
jmdns-main\src\main\java\javax\jmdns\impl\JmDNSImpl.java
 info.wait(200) in waitForInfoData is notified by other services. 

` private void waitForInfoData(ServiceInfo info, long timeout) {
        synchronized (info) {
            long loops = (timeout / 200L);
            if (loops < 1) {
                loops = 1;
            }
            for (int i = 0; i < loops; i++) {
                if (info.hasData()) {
                    break;
                }
                try {
                    info.wait(200);
                } catch (final InterruptedException e) {
                    /* Stub */
                }
            }
        }
    }`

\jmdns-main\src\main\java\javax\jmdns\impl\ServiceInfoImpl.java,   this.notifyAll(); is called by other records.

`    @Override
    public void updateRecord(final DNSCache dnsCache, final long now, final DNSEntry dnsEntry) {

        // some logging for debugging purposes
        if ( !(dnsEntry instanceof DNSRecord) ) {
            logger.trace("DNSEntry is not of type 'DNSRecord' but of type {}",
                    null == dnsEntry ? "null" : dnsEntry.getClass().getSimpleName()
            );
            return;
        }

        final DNSRecord record = (DNSRecord) dnsEntry;

        // flag for changes
        boolean serviceChanged = false;

        // When a record is soon to be expired, i.e. ttl=1, consider that as expired too. 
        if (record.isExpired(now)) {
            // remove data
            serviceChanged = handleExpiredRecord(record);
        } else {
            // add or update data
            serviceChanged = handleUpdateRecord(dnsCache, now, record);
        }

        // handle changes in service
        // things have changed => have to inform listeners
        if (serviceChanged) {
            final JmDNSImpl dns = this.getDns();
            if (dns != null) {
                // we have enough data, to resolve the service
                if (this.hasData()) {
                    // ServiceEvent event = ((DNSRecord) rec).getServiceEvent(dns);
                    // event = new ServiceEventImpl(dns, event.getType(), event.getName(), this);
                    // Failure to resolve services - ID: 3517826
                    //
                    // There is a timing/ concurrency issue here.  The ServiceInfo object is subject to concurrent change.
                    // e.g. when a device announce a new IP, the old IP has TTL=1.
                    //
                    // The listeners runs on different threads concurrently. When they start and read the event,
                    // the ServiceInfo is already removed/ changed.
                    //
                    // The simple solution is to clone the ServiceInfo.  Therefore, future changes to ServiceInfo 
                    // will not be seen by the listeners.
                    //
                    // Fixes ListenerStatus warning "Service Resolved called for an unresolved event: {}"
                    ServiceEvent event = new ServiceEventImpl(dns, this.getType(), this.getName(), this.clone());
                    dns.handleServiceResolved(event);
                }
            } else {
                logger.debug("JmDNS not available.");
            }
        }

        // This is done, to notify the wait loop in method JmDNS.waitForInfoData(ServiceInfo info, int timeout);
        synchronized (this) {
            this.notifyAll();
        }
    }`

Proposed fix: only notify when service has changes
`    @Override
    public void updateRecord(final DNSCache dnsCache, final long now, final DNSEntry dnsEntry) {

        // some logging for debugging purposes
        if ( !(dnsEntry instanceof DNSRecord) ) {
            logger.trace("DNSEntry is not of type 'DNSRecord' but of type {}",
                    null == dnsEntry ? "null" : dnsEntry.getClass().getSimpleName()
            );
            return;
        }

        final DNSRecord record = (DNSRecord) dnsEntry;

        // flag for changes
        boolean serviceChanged = false;

        // When a record is soon to be expired, i.e. ttl=1, consider that as expired too. 
        if (record.isExpired(now)) {
            // remove data
            serviceChanged = handleExpiredRecord(record);
        } else {
            // add or update data
            serviceChanged = handleUpdateRecord(dnsCache, now, record);
        }

        // handle changes in service
        // things have changed => have to inform listeners
        if (serviceChanged) {
            final JmDNSImpl dns = this.getDns();
            if (dns != null) {
                // we have enough data, to resolve the service
                if (this.hasData()) {
                    // ServiceEvent event = ((DNSRecord) rec).getServiceEvent(dns);
                    // event = new ServiceEventImpl(dns, event.getType(), event.getName(), this);
                    // Failure to resolve services - ID: 3517826
                    //
                    // There is a timing/ concurrency issue here.  The ServiceInfo object is subject to concurrent change.
                    // e.g. when a device announce a new IP, the old IP has TTL=1.
                    //
                    // The listeners runs on different threads concurrently. When they start and read the event,
                    // the ServiceInfo is already removed/ changed.
                    //
                    // The simple solution is to clone the ServiceInfo.  Therefore, future changes to ServiceInfo 
                    // will not be seen by the listeners.
                    //
                    // Fixes ListenerStatus warning "Service Resolved called for an unresolved event: {}"
                    ServiceEvent event = new ServiceEventImpl(dns, this.getType(), this.getName(), this.clone());
                    dns.handleServiceResolved(event);
                }
                // This is done, to notify the wait loop in method JmDNS.waitForInfoData(ServiceInfo info, int timeout);
                synchronized (this) {
                    this.notifyAll();
                }
            } else {
                logger.debug("JmDNS not available.");
            }
        }
    }`

Is posisble to include the fix in next release?

**Comment by zhangl22000** [comment]
> Environment:
> 
> 1. There are 120 systems which registers a serivce seperately.
> 2. Each system calls getServiceInfo every 100 seconds.
> 
> getServiceInfo get null value sometimes.
> 
> Root cause: jmdns-main\src\main\java\javax\jmdns\impl\JmDNSImpl.java info.wait(200) in waitForInfoData is notified by other services.
> 
> ` private void waitForInfoData(ServiceInfo info, long timeout) { synchronized (info) { long loops = (timeout / 200L); if (loops < 1) { loops = 1; } for (int i = 0; i < loops; i++) { if (info.hasData()) { break; } try { info.wait(200); } catch (final InterruptedException e) { /* Stub */ } } } }`
> 
> \jmdns-main\src\main\java\javax\jmdns\impl\ServiceInfoImpl.java, this.notifyAll(); is called by other records.
> 
> ` @OverRide public void updateRecord(final DNSCache dnsCache, final long now, final DNSEntry dnsEntry) {
> 
> ```
>     // some logging for debugging purposes
>     if ( !(dnsEntry instanceof DNSRecord) ) {
>         logger.trace("DNSEntry is not of type 'DNSRecord' but of type {}",
>                 null == dnsEntry ? "null" : dnsEntry.getClass().getSimpleName()
>         );
>         return;
>     }
> 
>     final DNSRecord record = (DNSRecord) dnsEntry;
> 
>     // flag for changes
>     boolean serviceChanged = false;
> 
>     // When a record is soon to be expired, i.e. ttl=1, consider that as expired too. 
>     if (record.isExpired(now)) {
>         // remove data
>         serviceChanged = handleExpiredRecord(record);
>     } else {
>         // add or update data
>         serviceChanged = handleUpdateRecord(dnsCache, now, record);
>     }
> 
>     // handle changes in service
>     // things have changed => have to inform listeners
>     if (serviceChanged) {
>         final JmDNSImpl dns = this.getDns();
>         if (dns != null) {
>             // we have enough data, to resolve the service
>             if (this.hasData()) {
>                 // ServiceEvent event = ((DNSRecord) rec).getServiceEvent(dns);
>                 // event = new ServiceEventImpl(dns, event.getType(), event.getName(), this);
>                 // Failure to resolve services - ID: 3517826
>                 //
>                 // There is a timing/ concurrency issue here.  The ServiceInfo object is subject to concurrent change.
>                 // e.g. when a device announce a new IP, the old IP has TTL=1.
>                 //
>                 // The listeners runs on different threads concurrently. When they start and read the event,
>                 // the ServiceInfo is already removed/ changed.
>                 //
>                 // The simple solution is to clone the ServiceInfo.  Therefore, future changes to ServiceInfo 
>                 // will not be seen by the listeners.
>                 //
>                 // Fixes ListenerStatus warning "Service Resolved called for an unresolved event: {}"
>                 ServiceEvent event = new ServiceEventImpl(dns, this.getType(), this.getName(), this.clone());
>                 dns.handleServiceResolved(event);
>             }
>         } else {
>             logger.debug("JmDNS not available.");
>         }
>     }
> 
>     // This is done, to notify the wait loop in method JmDNS.waitForInfoData(ServiceInfo info, int timeout);
>     synchronized (this) {
>         this.notifyAll();
>     }
> }`
> ```
> 
> Proposed fix: ` @OverRide public void updateRecord(final DNSCache dnsCache, final long now, final DNSEntry dnsEntry) {
> 
> ```
>     // some logging for debugging purposes
>     if ( !(dnsEntry instanceof DNSRecord) ) {
>         logger.trace("DNSEntry is not of type 'DNSRecord' but of type {}",
>                 null == dnsEntry ? "null" : dnsEntry.getClass().getSimpleName()
>         );
>         return;
>     }
> 
>     final DNSRecord record = (DNSRecord) dnsEntry;
> 
>     // flag for changes
>     boolean serviceChanged = false;
> 
>     // When a record is soon to be expired, i.e. ttl=1, consider that as expired too. 
>     if (record.isExpired(now)) {
>         // remove data
>         serviceChanged = handleExpiredRecord(record);
>     } else {
>         // add or update data
>         serviceChanged = handleUpdateRecord(dnsCache, now, record);
>     }
> 
>     // handle changes in service
>     // things have changed => have to inform listeners
>     if (serviceChanged) {
>         final JmDNSImpl dns = this.getDns();
>         if (dns != null) {
>             // we have enough data, to resolve the service
>             if (this.hasData()) {
>                 // ServiceEvent event = ((DNSRecord) rec).getServiceEvent(dns);
>                 // event = new ServiceEventImpl(dns, event.getType(), event.getName(), this);
>                 // Failure to resolve services - ID: 3517826
>                 //
>                 // There is a timing/ concurrency issue here.  The ServiceInfo object is subject to concurrent change.
>                 // e.g. when a device announce a new IP, the old IP has TTL=1.
>                 //
>                 // The listeners runs on different threads concurrently. When they start and read the event,
>                 // the ServiceInfo is already removed/ changed.
>                 //
>                 // The simple solution is to clone the ServiceInfo.  Therefore, future changes to ServiceInfo 
>                 // will not be seen by the listeners.
>                 //
>                 // Fixes ListenerStatus warning "Service Resolved called for an unresolved event: {}"
>                 ServiceEvent event = new ServiceEventImpl(dns, this.getType(), this.getName(), this.clone());
>                 dns.handleServiceResolved(event);
>             }
>             // This is done, to notify the wait loop in method JmDNS.waitForInfoData(ServiceInfo info, int timeout);
>             synchronized (this) {
>                 this.notifyAll();
>             }
>         } else {
>             logger.debug("JmDNS not available.");
>         }
>     }
> }`
> ```
> 
> Is posisble to include the fix in next release?

**Comment by kaikreuzer** [comment]
Could you create a PR with the proposed fix? That's much easier to read and could directly be merged if ok.

**Comment by zhangl22000** [comment]
@kaikreuzer  I created PR [https://github.com/jmdns/jmdns/pull/235/files](https://github.com/jmdns/jmdns/pull/235/files)  Please let me know if you have any questions.

Would you please share when the next release will be delivered? We need this info to see if it can catch up the schedule in my development.

**Comment by zhangl22000** [comment]
@kaikreuzer Would you have a chance to review the PR and share the info that whether this PR can be included in next release?

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/jmdns/jmdns/pull/235
