### ISSUE TITLE
ServiceInfo returns address as null:8080 and unable to access .local address

### ISSUE THREAD

**Issue by KDSbami** [jmdns/jmdns#236]
var jmdns = JmDNS.create(InetAddress.getLocalHost()) <---------------- localhost/127.0.0.1
var systemHostname: String = jmdns.hostName
if (systemHostname.endsWith(".")) {
    systemHostname = systemHostname.substring(0, systemHostname.length - 1)
}
Log.wtf("hostname: ",systemHostname) <---------------- localhost.local
val txt: HashMap<String,String> = HashMap<String,String>()
txt["path"] = "/"
val serviceInfo: ServiceInfo = ServiceInfo.create( "_http", "example_name", 8080, 0, 0, txt)

Log.wtf("inetAddress: ",serviceInfo.hostAddress+"..") <---------------- ..
Log.wtf("service info",serviceInfo.toString()) <------------- null:8080 in address
jmdns.registerService(serviceInfo)

**Comment by melloware** [comment]
I can't reproduce this. Can you provide a reproducer or close the ticket?

**Comment by KDSbami** [comment]
Can be closed. I don't remember why was this posted.
