### ISSUE TITLE
www.jmdns.org website is offline

### ISSUE THREAD

**Issue by bjhargrave** [jmdns/jmdns#237]
Attempting to access the http://www.jmdns.org/ website yields a message that the domain is now reserved.

**Comment by kaikreuzer** [comment]
Thanks for noticing! I have changed the provider and today the domain name became reassigned. Should be fixed now!

**Comment by bjhargrave** [comment]
Not fixed for me, at least not yet.

**Comment by bjhargrave** [comment]
Now the domain redirects to this github repo. So previously valid URLs like <http://www.jmdns.org/update-site/3.5.4/> are now 404.

**Comment by kaikreuzer** [comment]
> So previously valid URLs like http://www.jmdns.org/update-site/3.5.4/ are now 404.

This was always a 404. But http://www.jmdns.org/update-site/3.5.4/content.jar resolves correctly, so the update sites should work as expected.
