### ISSUE TITLE
IPv6 related NPE in ServiceInfoImpl.getHostAddresses()

### ISSUE THREAD

**Issue by bubbleguuum** [jmdns/jmdns#245]
jmdns version: 3.5.6. 

I've got a few automated crash reports with this stack trace, with `getHostAddress()` called in a `ServiceListener.serviceResolved()` callback:

```
Caused by: java.lang.NullPointerException
at javax.jmdns.impl.ServiceInfoImpl.getHostAddresses(ServiceInfoImpl.java:420)
at javax.jmdns.impl.ServiceInfoImpl.getHostAddress(ServiceInfoImpl.java:404)
```

looking at `getHostAddresses()`:

```
 @Override
    public String[] getHostAddresses() {
        Inet4Address[] ip4Aaddresses = this.getInet4Addresses();
        Inet6Address[] ip6Aaddresses = this.getInet6Addresses();
        String[] names = new String[ip4Aaddresses.length + ip6Aaddresses.length];
        for (int i = 0; i < ip4Aaddresses.length; i++) {
            names[i] = ip4Aaddresses[i].getHostAddress();
        }
        for (int i = 0; i < ip6Aaddresses.length; i++) {
            names[i + ip4Aaddresses.length] = "[" + ip6Aaddresses[i].getHostAddress() + "]";    
        }
        return names;
    }
```

line 420 is:

```
names[i + ip4Aaddresses.length] = "[" + ip6Aaddresses[i].getHostAddress() + "]";    
```

The only possible thing `null` on that line is `ip6Aaddresses[i]`. 
So I suppose `getInet6Addresses()` can return an `Inet6Address[]` where some elements are `null`.

I have not checked if v3.5.8 would fix this issue but I doubt it. 
Anyway, since my program does not make use of ipv6 at all, I worked-around this issue issue calling `ServiceInfoImpl.getInet4Address().getHostAddress()`.
Still it would be nice to get the bottom line of that NPE.

**Comment by ViToni** [comment]
Error is also present with v3.5.8.

**Comment by usnasoft** [comment]
This issue is probably retated to issue "ipv6 #260"

**Comment by ViToni** [comment]
It is not in my case as it happened on Java 8 which is not mentioned in the JDK bug.

**Comment by kaikreuzer** [comment]
If anyone is able to reproduce/debug it and provide a PR, I'm happy to merge it and do a new patch release.

**Comment by melloware** [comment]
@bubbleguuum please review my PR.
