### ISSUE TITLE
JMDNS responds to all Type A resolve hostname messages

### ISSUE THREAD

**Issue by bszland** [jmdns/jmdns#259]
JMDNS will respond to _any_ Type A/AAAA message it sees. For example, if attempting to resolve a particular hostname w/ avahi 

**`avahi-resolve-host-name --name nodeabc.local`**

JMDNS will respond regardless of if it's running on **nodeabc**. 

It seems like there's no check for the Query name:

https://github.com/jmdns/jmdns/blob/020e7ccbcbc3ecd0f0139dd007acb24153e4510e/src/main/java/javax/jmdns/impl/DNSQuestion.java#L37

like there is for service:

https://github.com/jmdns/jmdns/blob/020e7ccbcbc3ecd0f0139dd007acb24153e4510e/src/main/java/javax/jmdns/impl/DNSQuestion.java#L134

**Comment by torandreroland** [comment]
I'm seeing the same thing with an Eversolo DMP-A6 streamer that utilizes this library.

There is back and forth between my IKEA Dirigera Gateway (that queries for a host) and the Eversolo streamer responding irrespective of actually using that hostname. This causes my whole network to be flooded and useless.

Can you look into this issue?

**Comment by melloware** [comment]
PR submitted
