### ISSUE TITLE
Package Rename: javax is Oracle trademark, rename

### ISSUE THREAD

**Issue by melloware** [jmdns/jmdns#289]
See: https://www.infoq.com/news/2019/05/end-of-javax-package/

I know its been like this forever but really this is a violation of Oracle and its the reason everything moved to Jakarta package naming.

This should probably be `org.jmdns` or `com.github.jmdns` or something else.

**Comment by kaikreuzer** [comment]
The [use of this namespace](https://github.com/jmdns/jmdns/commit/4dfb9711a342d6d3badafc7a40f3c2a74e88f86f) predates any Oracle copyrights. From the blogpost you linked, I understand that the Eclipse Foundation agreed to not use the namespace for any specification work and future libraries, while using it "as-is" wouöd be ok.
As changing the namespace would break everybodys code, I would not do this step for no reason.

If Oracle themself is not permitting us the continued use (with really only patching a decades old library) and reaches out to us directly, I am willing to create a new major release of JmDNS with a changed namespace, which is not backward compatible and breaks everyone's code. Until then, I reject this issue for the best interest of our users.

**Comment by melloware** [comment]
@kaikreuzer i totally understand and thanks for responding.
