### ISSUE TITLE
Enhancements for JmDNS github repository configuration

### ISSUE THREAD

**Issue by janossch** [jmdns/jmdns#297]
To make **JmDNS** more attractive for consumers/developers:

1. Imho it would be better to have it explicitly expressed that _JAVA_ really is the most used language (instead of _HTML_) within the project. I believe [linguist](https://github.com/github-linguist/linguist/blob/main/docs/overrides.md) configuration needs to be adapted/utilized to modify on this.
![image](https://github.com/user-attachments/assets/a175b348-e110-4aae-a6d5-d0be5975a464)

2. additionally, the repository could be classified with topics, it would be a beneficial to have e.g. "zeroconf", "service-discovery", "mdns" topics added. Please add further suggestions in comments section. [More information about github topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics).

What is your opinion?

**Comment by melloware** [comment]
Agreed and you could probably add `avahi`, and `rendezvous` for tags as well.

**Comment by ViToni** [comment]
> Agreed and you could probably add `avahi`, and `rendezvous` for tags as well.

Using "avahi" feels a bit like SEO as Avahi is a different implementation of mDNS and that's IMO the only common factor. 

The term "rendezvous" has been dropped by Apple itself due to a trademark issue with Tibco, so ....

**Comment by melloware** [comment]
Good points.  

Rendezvous is legacy term but this lib was originally JRenedzvous before the spec was finalized and most users treat "avahi" as synonymous with MDNS on Linux.  

Feel free to ignore.

**Comment by kaikreuzer** [comment]
I've added the topics suggested by @janossch and ignored the ones from @melloware (sorry 😉) due to @ViToni's valid points.

Wrt (1), would anybody have a suggestion what `.gitattributes` content should be added? Feel free to create a PR yourself for it!

**Comment by janossch** [comment]
@kaikreuzer I can create a PR for it. But before that:

**Solution 1:**
The first obvious solution which came into my mind is to have a `.gitattributes` with this content:

```
devdocs/* linguist-documentation
src/site/* linguist-documentation
```

**Solution 2:**

```
src/site/* linguist-documentation
```
As you can see we can omit the first line if:

**a.** move `devdocs` folder under a main `docs` folder OR
**b.** just simply rename `devdocs` to `docs`
In this way there is no need to include it as an override for [linguist](https://github.com/github-linguist/linguist/blob/main/lib/linguist/documentation.yml) as linguist excludes some documentation files already by default.

Which one you prefer? **1, 2a or 2b**?

**Comment by kaikreuzer** [comment]
I would not touch the docs for now and thus go with (1).
I'm actually not sure about the status of `src/site` and `devdocs` - both folders have not been touched for many years and are likely pretty outdated (apart from the official specs that are there as txt files). Might be worth to look into the docs as well and possibly publish it to github-pages (for whatever is up-to-date and still relevant).

**Comment by ViToni** [comment]
> I'm actually not sure about the status of `src/site` and `devdocs` - both folders have not been touched for many years and are likely pretty outdated (apart from the official specs that are there as txt files). Might be worth to look into the docs as well and possibly publish it to github-pages (for whatever is up-to-date and still relevant).

I rememeber to have touched the `devdocs` folder some years back...
Based on current knowledge I'd suggest to remove the RFC files from the folder and reference the one from IETF (these are more up-to-date).  Also we don't need any experimental / DRAFT RFCs anymore.
Maybe even convert the HTML index file to Markdown so that it is usable directly from GitHub UI.
