### ISSUE TITLE
Not finding service sometimes

### ISSUE THREAD

**Issue by alg** [jmdns/jmdns#31]
Hi there!

Thanks for the great library. I'm writing an Android app that needs to discover a service on the local network and send some data upon an event. My issue is that the discovery is very unreliable and I can't seem to diagnose the problem just yet. To let it find the service I have to re-register the service by restarting the service app.

I'm monitoring the list of registered services with dns-sd and can see it there, but Android app can't. Not sure where to go from here. Please advise.

**Comment by kaikreuzer** [comment]
I suggest to close this and re-open if you have a reproducible case or at least some logs.

**Comment by alg** [comment]
:+1:
