### ISSUE TITLE
Loggers should be declared non-static

### ISSUE THREAD

**Issue by ViToni** [jmdns/jmdns#323]
Loggers are declared as `private static final`. This can have impact when having the library deployed on "shared" classpaths. 
It is prefereable to have them `non-static`.
If we care about serialization (which I don't assume) Loggers could be changed to be also `transient`.

For reference see:
- http://slf4j.org/faq.html#declared_static
- https://cwiki.apache.org/confluence/display/COMMONS/Logging+StaticLog

OpenHAB follows such a policy:
- https://www.openhab.org/docs/developer/guidelines.html#f-logging

**Comment by melloware** [comment]
ok if HAL follows that I am ok with it but in 20 years I have never run into an issue with a `static final logger`.   IntelliJ kept recommending this change on all classes as its their best practice for loggers to be static.  Same with SonarCube. cc @janossch since he and I both just made this change.

**Comment by ViToni** [comment]
It can be an issue when using dynmaic class loading such as it is done within an OSGi framework (and only if one updates JARs at runtime).

BTW I already prepared a PR, but waiting for #325 to be merged.

**Comment by melloware** [comment]
Thanks @ViToni !

**Comment by janossch** [comment]
@melloware I touched several `Logger` fields with my commits, but I've not changed any of them to `static` (yet). On the other hand if I would seen one I would have changed it to `static` without even thinking ... so your intuition is quite good 😄 

@ViToni as far as i understand this is an edge case where shared `ClassLoader` is used.. right? What could go wrong? You see mixed log lines from the server application and you can't correlate which application logged which entry, or what? Please don't get me wrong I'm just curious.

**Comment by ViToni** [comment]
@janossch Things can get complicated. In the most simple scenario one just looses memory since static references are bound to classes and not objects. In the worst case one can get `ClasCastException`s.
If one has a simple application which is started and shutdown, it's not an issue. If one has a dynmic environment such as application server or OSGi and also uses live updates this can very easily lead to issues.

It boils down to how class loading and garbage collection work in Java.
So these would be the topics if you are interested to go deeper.

**Comment by janossch** [comment]
@ViToni why `Logger` is the only static reference which could cause such a mess? Based on what you decribed so far I would not use `static` at all.
Are there any blogs or other sources where I can read about this more deeper?

**Comment by ViToni** [comment]
@janossch Because `Logger` is a dependency for this project (which could be updated as runtime) and Loggers are common to be used as `static` fields ( which might be totally depending on your application)

IMO the JLS is a good start: https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-4.3.4

**Comment by melloware** [comment]
PR submitted

**Comment by melloware** [comment]
@ViToni see my PR its failing all over because loggers are used in static context and must be static?  And they were previously static all we did was mark them `final`?
