### ISSUE TITLE
App exit in Android due to lack of try/catch in impl.DNSRecord 

### ISSUE THREAD

**Issue by lutusp** [jmdns/jmdns#34]
In recent Android versions, apps can manipulate the network parameters in such a way that jmdns causes an abrupt app exit. My Android app SSHelper started exiting in this way, and I traced it to DNSRecord.sameValue(). This patch fixes the problem:

-----------------------------------------------------------------------

    diff -Naur a/DNSRecord.java b/DNSRecord.java
    --- a/DNSRecord.java	2015-10-30 00:41:16.000000000 -0700
    +++ b/DNSRecord.java	2015-10-30 00:50:19.000000000 -0700
    @@ -308,14 +308,19 @@
     
     		@Override
     		boolean sameValue(DNSRecord other) {
    -			if (!(other instanceof Address)) {
    +			try {
    +				if (!(other instanceof Address)) {
    +					return false;
    +				}
    +				Address address = (Address) other;
    +				if ((this.getAddress() == null) && (address.getAddress() != null)) {
    +					return false;
    +				}
    +				return this.getAddress().equals(address.getAddress());
    +			} catch (Exception e) {
    +				e.printStackTrace();
     				return false;
     			}
    -			Address address = (Address) other;
    -			if ((this.getAddress() == null) && (address.getAddress() != null)) {
    -				return false;
    -			}
    -			return this.getAddress().equals(address.getAddress());
     		}
     
     		@Override
    -----------------------------------------------------------------------

I don't know much about Github, I hope this is an appropriate way to report a bug. Apropos: http://xkcd.com/1597/

**Comment by Flowdalic** [comment]
Out of curiosity: Could you show us the stacktrace of the exception you encountered?

Also I'd recommend using a JUL logger instead of `e.printStackTrace()`. JUL works on Java SE and Android and will associate the stacktrace with a severity level, whereas using printStackTrace() just prints the trace to stderr (You should never use printStackTrace()).
