### ISSUE TITLE
After service discovery, ServiceInfo.getHostAddress() sometimes returns IP address is hex values?

### ISSUE THREAD

**Issue by erawhctim** [jmdns/jmdns#41]
I used the following code to request info about a service: 
```
JmDNS dns = new JmDNS();
ServiceInfo info = dns.getServiceInfo("type", "name", timeout);
```

The result eventually returns, the info is correct and I can fetch the IP address via `info.getHostAddress()`.

However, it seems that sometimes the address is returned like this: `fe80::e2ac:cbff:fe64:e3da`. Is this normal? Is this just the IP in hex values (or something similar) that I can convert back to int's pretty easily? I've never seen an address formed that way before.

**Comment by maggu2810** [comment]
That is an IPv6 address (not an IPv4 one).

**Comment by erawhctim** [comment]
Is there a way to specify that I only want to fetch IPv4 addresses?

**Comment by maggu2810** [comment]
What about this one:
https://github.com/jmdns/jmdns/blob/62891d41a88aec4451128692423c0b4619b0a618/src/main/java/javax/jmdns/ServiceInfo.java#L528
