### ISSUE TITLE
PTR or SRV to check for Service Remove Detection

### ISSUE THREAD

**Issue by nileshilpa** [jmdns/jmdns#48]
Hi there,

While testing jmDNS to use for our Android app, I noticed Service Removal took longer than an hour. 

Upon further investigation, found that Service removal only checks for PTR records, which usually have lot longer TTL..

Following code points to earlier version using both PTR and SRV to detect service removal.

https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/JmDNSImpl.java#L1257 

Any idea - why this change was reversed? 

Thanks,

**Comment by ViToni** [comment]
Maybe you could try if the release https://github.com/jmdns/jmdns/releases/tag/jmdns-3.5.2 works for you.

If the issue is not reproducible anymore the issue could be closed then.

**Comment by melloware** [comment]
@kaikreuzer almost 8 years and no response from original poster i would say this is safe to close.
