### ISSUE TITLE
JmmDNS.Factory.getInstance() races with JmmDNS.Factory.close()

### ISSUE THREAD

**Issue by cgutman** [jmdns/jmdns#49]
There's a race condition that can cause a JmmDNS object to be returned from the factory class as it's being closed (waiting inside jmmDNS.close()). This is leading to crashes in my application in rare cases.

Consider the following:
Thread 1 - Calls JmmDNS.Factory.close()
Thread 1 - JmmDNS.Factory.close() invokes JmmDNS.close() which shuts down some thread pools then waits on the underyling jmDNS objects to be closed.
Thread 2 - Calls JmmDNS.Factory.getInstance()
Thread 2 - In getInstance(), _instance != null so we don't wait on the factory lock (which would solve this issue). Instead we just return _instance (which is the instance being closed at the moment!) The _instance = null line in JmmDNS.Factory.close() has not been reached yet because the close isn't finished.
Thread 2 - Calls something like jmmDNS.requestServiceInfo() which throws a RejectedExecutionException because _jmDNSExecutor.shutdown() was already called.

The stack trace of the crash looks like this:
`java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@421c3660 rejected from java.util.concurrent.ThreadPoolExecutor@421aa328[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 132]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:81)
	at javax.jmdns.impl.JmmDNSImpl.requestServiceInfo(JmmDNSImpl.java:338)
	at javax.jmdns.impl.JmmDNSImpl.requestServiceInfo(JmmDNSImpl.java:327)`

I thought of a few potential fixes. The easiest one is just to remove the outer (_instance == null) check in JmmDNS.Factory.getInstance(). This causes thread 2 to block on the Factory's monitor while the close finishes.

Another possible fix would be to set _instance = null before calling jmmDNS.close(). This has the benefit of JmmDNS.Factory.getInstance() not being blocked by JmmDNS.Factory.close() as it would be if the monitor was held while waiting for the close to complete.

**Comment by cgutman** [comment]
Upon further thought, I think you have to remove the outer _instance == null check even if you choose to adopt the second fix. JmmDNS.Factory.getInstance() has a time of check to time of use error because _instance can be set to null by JmmDNS.Factory.close() between the time that the outer _instance == null check is evaluated and the time when _instance is returned.

Consider:
Thread 1 - JmmDNS.Factory.getInstance() called
Thread 1 - Checks _instance == null (which is false)
Thread 2 - Calls JmmDNS.Factory.close() which closes the jmmDNS object and sets _instance = null
Thread 1 - Returns _instance (which is now null)

**Comment by kaikreuzer** [comment]
If you create a PR by this afternoon, I would include this in 3.5.0 (which replaces the revoked 3.4.3).

**Comment by cgutman** [comment]
Sure thing. I'll get one prepared.

**Comment by kaikreuzer** [comment]
Sorry, too late for 3.5.0, but I will add it to an upcoming 3.5.1 then!

**Comment by ryanidev** [comment]
I'm not sure if it's the same problem or not, but I'm seeing the RejectedExecutionException when trying to run some instrumentation tests. I have a feeling it's because I'm shutting everything down, then spinning back up between each test, it seems like I'm getting a stale JmDns instance (I null out my instances of everything between tests).
