### ISSUE TITLE
serviceResolved not called on TYPE_A/AAAA record change

### ISSUE THREAD

**Issue by Idhor** [jmdns/jmdns#51]
When a service info is updated for a record TYPE_A or TYPE_AAAA change serviceResolved is not called again because https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/ListenerStatus.java#L117 doesn't check for address changes
All starts here https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/ServiceInfoImpl.java#L885
So if you want to filter only services that have IPv4 address sometimes you will skip some of them because they have only an IPv6 address and serviceResolved will never be called again when the TYPE_A record is parsed/resolved
It happens only sometimes because [serviceResolved](https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/ListenerStatus.java#L93) is executed on a thread pool and most of the times the service info already contains both addresses. I think that depends on the device speed, if i enable all debug loggings it happens more often

I'm not an expert of mDNS and i don't know if we just need a check for address changes in `_sameInfo` and if we should also avoid to dispatch multiple times `handleServiceResolved(event);` (that does an _executor.submit) if we already have all the data

**Comment by Idhor** [comment]
I have done a pull request that checks service info addresses but i'm not an expert of jmdns and i don't know if it is valid fix or an hack

**Comment by kaikreuzer** [comment]
I am not an expert either. Your fix seemed to make sense to me and hence I merged it. Let's touch wood that there aren't any unexpected side effects.
