### ISSUE TITLE
tag: 3.4.3 

### ISSUE THREAD

**Issue by maggu2810** [jmdns/jmdns#52]
The repo contains a
* jmdns-3.4.0 tag
* jmdns-3.4.1 tag
* jmdns-3.4.2 tag

but misses a "jmdns-3.4.3" tag.

Could you add one please?

**Comment by kaikreuzer** [comment]
No, because I [revoked the release](https://github.com/jmdns/jmdns/issues/50#issuecomment-187656425) and will do a 3.5.0 instead later today.
