### ISSUE TITLE
JmDNS 3.5.0: p2 Repo not available

### ISSUE THREAD

**Issue by maggu2810** [jmdns/jmdns#55]
> This release is also available on a p2 repository at http://www.jmdns.org/update-site/3.5.0

I get a "Page not found" if I visit http://www.jmdns.org/update-site/3.5.0

**Comment by kaikreuzer** [comment]
Well,you are not a p2 update agent, right?
A such you would check for http://www.jmdns.org/update-site/3.5.0/content.jar and notice that it is there :-)

**Comment by maggu2810** [comment]
> Well,you are not a p2 update agent, right?

You are right. :wink:  Time to sleep...
