### ISSUE TITLE
JmDNS 3.5.0 still says it is 3.4.2

### ISSUE THREAD

**Issue by talksinmath** [jmdns/jmdns#57]
Hi,

thanks a lot for the release - that is really great news for us!
Unfortunately I found a bug in it: The field `VERSION` in the Class `JmDNS` still contains `3.4.2` as the current version.
[Link to code](https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/JmDNS.java#L42l)

Best regards,
Carsten

**Comment by kaikreuzer** [comment]
Thanks for noticing, this is nasty to have the version in the Java code itself...
I'd actually suggest to remove it for future versions - for now we could set it to "3.x", what do you think?

**Comment by talksinmath** [comment]
Actually, I'd prefer to have the real version reported - or none at all. 
`3.x` does not proivde any informational valu, imho. 

Hope some more people chime in here ;)

**Comment by kaikreuzer** [comment]
> or none at all. 

Yes, but as it is a public field, removing it would break backward compatibility, that's why we have to keep the field in there (until a 4.x release).

**Comment by talksinmath** [comment]
True, I forgot that aspect. Still, `3.x` does feel weird..

**Comment by maggu2810** [comment]
If you really need a correct version string for the 3 version, you could
* setup maven to create a property file that contains the version(http://stackoverflow.com/a/2470071)
* add this property file to the bundle
* update the string value using the property file (but for non-osgi context this needs to be done in a static block)

For 4.x it should be removed.

@kaikreuzer You should perhaps create a tag with todos for the next major release or create a branch for that changes, so they get not lost.

**Comment by kaikreuzer** [comment]
Ok, I tagged it.
So what shall we do with the version until then? The property stuff is imho too complicated and not worth the effort.
How about simply putting "3" as a version in there?

**Comment by talksinmath** [comment]
I'd actually prefer to keep it around. I will give it a shot with the resource-file.

**Comment by talksinmath** [comment]
I'll close this one since it's been merged. Thanks!
