### ISSUE TITLE
Bring distribution to MavenCentral

### ISSUE THREAD

**Issue by iheart2code** [jmdns/jmdns#6]
We need to agree on how to distribute. I, admittedly, don't know a whole lot about Maven, but it seems like our choices are some combination of the following.

1. Gain access to update previous Maven entry
2. Create new Maven entry for this project
3. Provide links to each JAR release file

**Comment by kaikreuzer** [comment]
@spearway: What do you think about a creating a new release? We still have the task open to close down the sourceforge site - would be really great if we could eventually do this.

**Comment by virl** [comment]
Is someone alive here?

**Comment by kaikreuzer** [comment]
I am, but I operate only as a backup release manager... Anyhow, I just created a 3.4.2 release, although this won't be available on Maven Central for now.

**Comment by mvdan** [comment]
Would be very helpful if you could upload it to jcenter too :)

**Comment by virl** [comment]
Also if you will upload to jcenter, please upload with all the existing patches, so it will work on Android.

**Comment by brcolow** [comment]
May I suggest (at least temporarily) creating a new groupId and artifactId to publish version 3.4.2 to maven central? This would really help me out. If you ever get the credentials to post under javax.jmdns then you can go back and do that, but moving forward it would be really nice of 3.4.2 was in maven central under *some* groupId.

**Comment by virl** [comment]
@brcolow +1 to that. Currently you basically have to commit jmdns sources to your project. Very inconvenient.

**Comment by kaikreuzer** [comment]
Ok, as I haven't heard back from the original owners, I decided to publish it under the groupId org.openhab.jmdns. For the moment, it is available at https://dl.bintray.com/openhab/mvn/org/openhab/jmdns/jmdns/3.4.2/, I have also requested approval for uploading it to jcenter and Maven central, which should both happen in the coming days.

**Comment by virl** [comment]
@kaikreuzer Is it patched version that works on Android?

**Comment by kaikreuzer** [comment]
It is the same version as on https://github.com/openhab/jmdns/releases/tag/jmdns-3.4.2.
What needs to be patched for Android?

**Comment by virl** [comment]
@kaikreuzer it seems your version is fine.

**Comment by kaikreuzer** [comment]
Here we go, we are on jcenter: https://jcenter.bintray.com/org/openhab/jmdns/jmdns/3.4.2/

**Comment by virl** [comment]
@kaikreuzer great. Thanks.

**Comment by maggu2810** [comment]
Please inform, if it is uploaded to Maven central (if you will be notified).

**Comment by kaikreuzer** [comment]
I was granted access, but I didn't yet upload the release, since we are not fulfilling the requirements: http://central.sonatype.org/pages/requirements.html

JavaDoc and GPG signature are definitely still missing, meta-data needs to be checked, if complete.
If anybody could deal with JavaDoc and meta-data, I will try to GPG sign it and upload it.

**Comment by brcolow** [comment]
Javadoc can be generated like so:

````xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-javadoc-plugin</artifactId>
	<version>2.10.3</version>
	<configuration>
		<outputDirectory>${project.build.directory}/javadoc</outputDirectory>
	</configuration>
	<executions>
		<execution>
			<id>attach-javadocs</id>
			<goals>
				<goal>jar</goal>
			</goals>
			<configuration>
				<additionalparam>-Xdoclint:none</additionalparam>
			</configuration>
		</execution>
	</executions>
</plugin>
````

**Comment by kaikreuzer** [comment]
Ok, a javadoc jar is added: https://jcenter.bintray.com/org/openhab/jmdns/jmdns/3.4.2/:jmdns-3.4.2-javadoc.jar

Will have to look into the GPG signing, I hope I find the time in the next days for it.

**Comment by mvdan** [comment]
Anyone getting these when switching from 3.4.1 to the 3.4.2 jar found on jcenter?

```
Warning: javax.jmdns.impl.DNSCache: can't find referenced method 'java.util.concurrent.ConcurrentHashMap$KeySetView keySet()' in program class javax.jmdns.impl.DNSCache
Warning: javax.jmdns.impl.DNSCache: can't find referenced class java.util.concurrent.ConcurrentHashMap$KeySetView
Warning: javax.jmdns.impl.DNSCache: can't find referenced class java.util.concurrent.ConcurrentHashMap$KeySetView
```

**Comment by maggu2810** [comment]
IIRC This could be mixed code compiled with 1.8 and 1.7.
https://gist.github.com/AlainODea/1375759b8720a3f9f094

**Comment by maggu2810** [comment]
The JmDNS on jcenter was created using 1.8.
See Manifest: Build-Jdk: 1.8.0_40

We should build it with 1.7, so it could be used with 1.7 and 1.8.

**Comment by mvdan** [comment]
Yes, definitely. A jar built with 1.8 is useless for Android apps, since most of them build with 1.7.

**Comment by kaikreuzer** [comment]
> We should build it with 1.7, so it could be used with 1.7 and 1.8.

Sorry for that. I just replaced it with a version that was built with Java 1.7.
You'll probably have to clean your local maven repo first.

**Comment by mvdan** [comment]
Works fine now, thank you!

**Comment by kaikreuzer** [comment]
I think I will leave it with JCenter for this release and not upload it to Maven Central, since I actually fail to do so since some meta-data is missing in the pom.xml.
I have added the missing stuff to master, so the next release should be fine to be pushed to Maven Central.
Unless anybody really thinks it is a must, I will close this issue.

**Comment by janvlug** [comment]
Should this issue really be closed before a new version has been released to MavenCentral?
I really would like to see jmdns available on MavenCentral.

**Comment by kaikreuzer** [comment]
Ok, as you wish :-)

**Comment by janvlug** [comment]
Are there any plans to bring jmdns 3.4.3 to MavenCentral?

**Comment by kaikreuzer** [comment]
Yes, it is available on JCenter since this morning, MavenCentral is the next step now.

**Comment by maggu2810** [comment]
I cannot find it on https://jcenter.bintray.com/
I have looked at group org.jmdns and org.openhab.jmdns
Could you point me to the artifact?

**Comment by maggu2810** [comment]
Okay... https://github.com/jmdns/jmdns/issues/50#issuecomment-187656425

**Comment by mvdan** [comment]
Did any of you remove 3.4.2 from jcenter? You just broke our build :(

**Comment by kaikreuzer** [comment]
https://jcenter.bintray.com/org/openhab/jmdns/jmdns/3.4.2/

I must admit that I accidentially removed it for a few minutes yesterday.
What exactly fails about your build?

**Comment by mvdan** [comment]
CI failed yesterday because of it vanishing, so I assumed it was still gone. Thanks for quickly fixing it.

**Comment by mvdan** [comment]
Failed again - you uploaded a different artifact now!

```
Checksum failed for org.openhab.jmdns:jmdns:7a4b34b5606bbd2aff7fdfe629edcb0416fccd367fb59a099f210b9aba4f0bce
```

Did you upload a different 3.4.2 build? This breaks building all of our recent tags.

**Comment by kaikreuzer** [comment]
Yes, indeed, the artifact has a new checksum. I am not sure if I have the original artefacts at hand - feel free to send the old content of https://jcenter.bintray.com/org/openhab/jmdns/jmdns/3.4.2/ to me and I will replace them there.

**Comment by mvdan** [comment]
What email address? I should have the jar cached.

**Comment by eighthave** [comment]
Thanks for your work reviving jmdns!

As far as I understand it, if you publish to mavenCentral, it'll automatically get mirrored onto jCenter, but not vice-versa.  So publishing to mavenCentral would be preferable so its available on both.

**Comment by kaikreuzer** [comment]
> What email address?

kai (at) openhab (dot) org

**Comment by mvdan** [comment]
I uploaded it to my server temporarily in case anyone else needs it: https://mvdan.cc/tmp/jmdns-3.4.2.jar

Verified the sha256, it's correct.

**Comment by eighthave** [comment]
Looks like 3.4.3 did not make it to the main public repo yet:
https://jcenter.bintray.com/org/openhab/jmdns/jmdns/

I think you have to click "publish" in the bintray UI to send it to that repo like the 3.4.2 release.

**Comment by mvdan** [comment]
@eighthave he did that on purpose, 3.4.3 was a bad release. See 3.5.0.

**Comment by eighthave** [comment]
Ok, found it: https://jcenter.bintray.com/org/jmdns/jmdns/3.5.0  aka:

```
        compile 'org.jmdns:jmdns:3.5.0'
```


@kaikreuzer this is great, I think org.jmdns is perfect, especially since its an actual website owned by this project :)

**Comment by virl** [comment]
Just wanted to say thanks to everyone here for reviving jmdns. It is much needed project — I use its code in many of my projects.

**Comment by kaikreuzer** [comment]
> I uploaded it to my server temporarily in case anyone else needs it: https://mvdan.cc/tmp/jmdns-3.4.2.jar

Ok, I uploaded this now and created an according md5 file. I hope that we do not have to replace the pom.xml as well. Please have a try, if this solves the problem!

> @kaikreuzer this is great, I think org.jmdns is perfect, especially since its an actual website owned by this project :)

Yes, I also thought it is best to have a neutral place to continue this project, so with the change of the groupId and the registration of the according domain name, this should be the best solution now.

> Just wanted to say thanks to everyone here for reviving jmdns. It is much needed project — I use its code in many of my projects.

Note that I am only running it as I need it myself and was fearing that it got lost on Sourceforge.
Since I am not a mDNS experts and hardly anyone of the original code authors is available anymore, the situation is anything but ideal. So whoever thinks he knows mDNS well enough and could help maintaining the project (i.e. reviewing PRs, creating fixes, etc.), please speak up! Everybody is invited to help out here and I am happy to add further people to the github jmdns organisation as a maintainer!

**Comment by mvdan** [comment]
Thanks @kaikreuzer! Triggering a CI build now.

**Comment by mvdan** [comment]
Confirming that the build works again. Thanks!

**Comment by kaikreuzer** [comment]
Glad to hear this and sorry again for the trouble!

**Comment by janvlug** [comment]
Back to topic after this intermezzo :)
Are there any plans to bring jmdns 3.5.0 to MavenCentral?

**Comment by janvlug** [comment]
I read through all the comments of this issue. Let me try to summarize:
The requirements for deploying to Maven Central are stated here:
http://central.sonatype.org/pages/requirements.html
The only missing requirement are the GPG/PGP signatures:
http://central.sonatype.org/pages/requirements.html#sign-files-with-gpgpgp
Detailed instructions on how to produce these can be found here:
http://central.sonatype.org/pages/working-with-pgp-signatures.html

Probably the signature of Kai Kreuzer should be used.

@kaikreuzer: would you be able to produce the signatures for the the JmDNS 3.5.0 released artifacts?
If you need any help with signing, please let me know. I can also generate the keys and signatures for you if you prefer so. In that case I will provide you the private key.

**Comment by eighthave** [comment]
I'm also happy to help getting up the GPG signatures.  The fun part is
that the private key should be kept on as secure a machine as possible

**Comment by kaikreuzer** [comment]
All, I think I know how to do it and I will take care of it. I am just terribly busy atm and didn't find the time yet - thanks for your patience!

**Comment by effad** [comment]
Just a quick note that I also would very much appreciate getting 3.5.0 from maven central.

**Comment by kaikreuzer** [comment]
Thank you all for your patience, now I have finally done it!
http://repo1.maven.org/maven2/org/jmdns/jmdns/3.5.1/
