### ISSUE TITLE
Hostname containing ':' and '%'

### ISSUE THREAD

**Issue by dhufnagel** [jmdns/jmdns#62]
If you use JmmDNS or JmDNS without providing a hostname, then the hostname built by the class "HostInfo" can contain ':' and '%' when using IPv6 addresses. For example on my link-local IPv6 address: 

> fe80:0:0:0:4011:df1c:2c27:a0b9%eth3.local.

 The '.' in IPv4 addresses are encapsulated in following line:
https://github.com/jmdns/jmdns/blob/master/src/main/java/javax/jmdns/impl/HostInfo.java#L107

I suggest to extend this line to also replace ':' and '%' as following: 
`aName = aName.replaceAll("[:%\\.]", "-");`

**Comment by kaikreuzer** [comment]
Fixed in #63
