### ISSUE TITLE
Missing source in release .3.5.0

### ISSUE THREAD

**Issue by jkiddo** [jmdns/jmdns#66]
Release 3.5.0 does not seem to have the sources bundled the standard way to the binaries when trying to look up the source

**Comment by kaikreuzer** [comment]
What exactly is "the standard way"?
All the sources are published along with the binaries at https://jcenter.bintray.com/org/jmdns/jmdns/3.5.0/.

**Comment by jkiddo** [comment]
My bad ... somehow my maven cache was screwed up
