### ISSUE TITLE
Please push 3.5.0 to maven central

### ISSUE THREAD

**Issue by dunmatt** [jmdns/jmdns#74]
The latest version of JmDNS on maven central is 3.4.2, which has a major bug in the way it generates TXT records, please push 3.5.0 so that future users who like managed dependencies don't have to learn all of this the hard way (as I did).  Thanks!  :-)

**Comment by maggu2810** [comment]
Have you read this one: https://github.com/jmdns/jmdns/issues/6#issuecomment-220250460

**Comment by dunmatt** [comment]
Aha, I hadn't seen that one, thanks!  I'll close this as duplicate.
