### ISSUE TITLE
Example code from the README is outdated and incomplete

### ISSUE THREAD

**Issue by rspielmann** [jmdns/jmdns#75]
Service Registration example from the README:
```
import javax.jmdns.*;

JmDNS jmdns = new JmDNS();
jmdns.registerService(
    new ServiceInfo("_http._tcp.local.", "foo._http._tcp.local.", 1234, 0, 0, "path=index.html")
);
```

1. JmDNS cannot be instantiated this way because it is abstract (probably wasn't abstract in an earlier version).
2. There should be complete code (including class Example and main) or a comment denoting that something has been left out.

Problem 2 is rather cosmetic, but a copy-paste-able example would probably be nice.

The "abstract" problem applies to the Service Discovery example too, as well as the cosmetic problem.

**Comment by effad** [comment]
I also just stumbled accross this problem.

**Comment by kaikreuzer** [comment]
@rspielmann Do you plan to create a PR to address these problems?

**Comment by rspielmann** [comment]
@kaikreuzer I just did :)

**Comment by kaikreuzer** [comment]
Wonderful, thanks - already merged :-)
