### ISSUE TITLE
Services that start with space or underscore are not found

### ISSUE THREAD

**Issue by namannik** [jmdns/jmdns#78]
The `serviceAdded` method is not called for services whose names start with a space or an underscore.  They do, however, appear in the Bonjour list on iOS and Mac.

There may be other characters that also cause this, but I haven't found others yet.  Other symbols I've tried don't seem to cause this issue.

**Comment by namannik** [comment]
This same issue occurs with services whose name start with a period.

**Comment by melloware** [comment]
@kaikreuzer this has been fixed and can be closed.
