### ISSUE TITLE
DNSStateTask setting default TTL

### ISSUE THREAD

**Issue by FMesmer** [jmdns/jmdns#81]
By setting DNSStateTask.setDefaultTTL(newDefaultTTLValue) a new default TTL can be set.
But in the code the value of the constant is still used. 
It would be helpful if at least in the DNSQuestion class in the method addAnswersForServiceInfo the "DNSConstants.DNS_TTL" value is replaced by "DNSStateTask.defaultTTL()".
With these changes the answer of an DNS question uses the new default TTL value.

As mentioned above their exists similar methods still using the constant value. But I am not sure if all occurrences should be replaced.

Regards
Frank

**Comment by kaikreuzer** [comment]
Could you create a PR with the suggested changes?

**Comment by kaikreuzer** [comment]
As discussed in https://github.com/jmdns/jmdns/pull/83#issuecomment-236016010, this isn't the right approach to tackle the problem, so I am closing this issue.
