### ISSUE TITLE
getExpirationTime overflow

### ISSUE THREAD

**Issue by Misterke** [jmdns/jmdns#93]
In real use we've noticed Bonjour (64bit) sending out A records with a very high (yet still positive) TTL, in the observed cases over 21474836.  This obviously is not a problem of JmDNS and in fact - apart from very long continued existence of the record if the site would go down without notification, it shouldn't be a problem at all, but ...

In JmDNS DNSRecord.getExpirationTime is implemented as:
```
    long getExpirationTime(int percent) {
        // ttl is in seconds the constant 10 is 1000 ms / 100 %
        return _created + (percent * _ttl * 10L);
    }
```

Here both percent and _ttl are of type int, so 32 bit signed integer.  With high values of _ttl, `percent * _ttl` can overflow.  With a value above 21474837 and an invocation for 100%, this gives a number above 2147483648 (0x80000000) and hence as a 32 bit signed integer becomes negative, causing the received packet to be considered as out-dated and being dropped.

I totally agree that the real problem here is Bonjour (or whatever triggers it to use these TTLs, since it isn't always the case), but at least the overflow in JmDNS causes robustness issues and can be very easily corrected by first casting _ttl to long.  So, can you modify the implementation of DNSRecord.getExpirationTime in the official code-base to the below?
```
    long getExpirationTime(int percent) {
        // ttl is in seconds the constant 10 is 1000 ms / 100 %
        return _created + (percent * ((long)_ttl) * 10L);
    }
```

**Comment by maggu2810** [comment]
For the valid range for TTL see here:
* https://tools.ietf.org/html/rfc1035#section-3.2.1
* https://tools.ietf.org/html/rfc2181#page-10

maximum value: 2147483647 (2^31 - 1)

JmDNS should be able to handle the maximum.
I don't think that the Bonjour implementation here is "the real problem".
It does not matter if such a high value make sense, the library should be able to handle every valid message internally (without overflows etc.).

So, your fix should be valid. If we would like to increase the number we received by the TTL field, we need to convert it to a long before.

**Comment by Misterke** [comment]
So, will the fix somehow be taken along?  Or do I have to fork, modify and enter a pull request for this small fix (I haven't done that on github yet)?

**Comment by kaikreuzer** [comment]
If you do not feel comfortable with git, I can do this change, no problem.
It seems that you have started trying it yourself already, though, so please let me know, what you prefer!

**Comment by Misterke** [comment]
GIT is not the problem, but I haven't made a pull-request or contributed to any project on github before.  So, losing some time in the contribution rules (reading some of it AFTER already having pushed ...).  Anyway, I've think there should now be a pull request https://github.com/jmdns/jmdns/pull/94 to address the same.  If I have still missed some contribution rule (well, I know I didn't get the signed off into the commit and only have it in the pull request), please let me know so I can improve for next time.

**Comment by kaikreuzer** [comment]
Thanks! This way, you at least get the tribute for the fix :-)
